version: '3'
services:
  users:
    build: https://github.com/dankolbman/stoic-users.git
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SECRET_KEY 
      - SSL_DISABLE
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:psql@postgres:5432/stoic
    command: ./manage.py runserver -h 0.0.0.0 -p 5000
    links:
      - "pg:postgres"
  images:
    build: https://github.com/dankolbman/stoic-images.git
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SECRET_KEY 
      - SSL_DISABLE
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:psql@postgres:5432/stoic
    command: ./manage.py runserver -h 0.0.0.0 -p 5000
    volumes:
      - image_uploads:/uploads
    links:
      - "pg:postgres"
  geo:
    build: https://github.com/dankolbman/stoic-geo.git
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY 
      - SSL_DISABLE
      - CASSANDRA_HOSTS=cassandra
    depends_on:
      - "cassandra"
      - "redis"
    command: ["./wait-for-it.sh", "cassandra:9042", "--", "./manage.py", "runserver", "-h", "0.0.0.0", "-p", "5000"]
    restart: always
    volumes:
      - csv_files:/app/csv_files
    links:
      - "cassandra:cassandra"
      - "redis:redis"
  trips:
    build: https://github.com/dankolbman/stoic-trips.git
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SECRET_KEY 
      - SSL_DISABLE
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:psql@postgres:5432/stoic
    depends_on:
      - "cassandra"
      - "redis"
    command: ./manage.py runserver -h 0.0.0.0 -p 5000
    restart: always
    links:
      - "pg:postgres"
  nginx:
    image: nginx:1.13
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    links:
      - users
      - geo
  celery:
    build: https://github.com/dankolbman/stoic-geo.git
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SECRET_KEY
      - SSL_DISABLE
      - CASSANDRA_HOSTS=cassandra
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CSV_UPLOAD_DIR=.
      - MAX_CONTENT_LENGTH=9999999999
    command: ["./wait-for-it.sh", "redis:6379", "--", "celery", "worker", "-l", "debug", "-A", "geo.tasks"]
    depends_on:
      - "redis"
    volumes:
      - csv_files:/app/csv_files
    links:
      - "cassandra:cassandra"
      - "redis:redis"
  pg:
    image: postgres:9.6
    volumes:
      - pgdata:/var/log/postgresql/data
    environment:
      POSTGRES_DB: stoic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
  redis:
    image: redis:3.2
  cassandra:
    image: cassandra:3.10
    volumes:
      - cassandradata:/var/lib/cassandra
volumes:
  pgdata:
    driver: local
  cassandradata:
    driver: local
  csv_files:
    driver: local
  image_uploads:
    driver: local
