version: '3'
services:
  users:
    image: kolbman.xyz:3333/users
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SSL_DISABLE
      - SECRET_KEY
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:psql@postgres:5432/stoic
    command: ./manage.py runserver -h 0.0.0.0 -p 5000
    links:
      - "pg:postgres"
  blog:
    image: kolbman.xyz:3333/blog
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SSL_DISABLE
      - SECRET_KEY
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:psql@postgres:5432/stoic
    command: gunicorn -w 4 -b :5000 wsgi:app
    links:
      - "pg:postgres"
  images:
    image: kolbman.xyz:3333/images
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SSL_DISABLE
      - SECRET_KEY
      - GEO_URL=http://geo:5000
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_BACKEND=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:psql@postgres:5432/stoic
      - IMAGE_UPLOAD_DIR=/images
    command: ./manage.py runserver -h 0.0.0.0 -p 5000
    volumes:
      - image_uploads:/images
    links:
      - "pg:postgres"
      - "geo:geo"
      - "redis"
  geo:
    image: kolbman.xyz:3333/geo
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SSL_DISABLE
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SECRET_KEY
      - CASSANDRA_HOSTS=cassandra
    depends_on:
      - "cassandra"
      - "redis"
    command: ["./wait-for-it.sh", "cassandra:9042", "--", "./manage.py", "runserver", "-h", "0.0.0.0", "-p", "5000"]
    restart: always
    volumes:
      - csv_files:/app/csv_files
    links:
      - "cassandra:cassandra"
      - "redis:redis"
  trips:
    image: kolbman.xyz:3333/trips
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SSL_DISABLE
      - SECRET_KEY
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:psql@postgres:5432/stoic
    depends_on:
      - "cassandra"
      - "redis"
    command: ./manage.py runserver -h 0.0.0.0 -p 5000
    restart: always
    links:
      - "pg:postgres"
  nginx:
    image: nginx:1.13
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - image_uploads:/images
    ports:
      - 8081:80
    links:
      - users
      - geo
  celery_geo:
    image: kolbman.xyz:3333/geo
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SECRET_KEY
      - SSL_DISABLE
      - CASSANDRA_HOSTS=cassandra
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CSV_UPLOAD_DIR=.
      - MAX_CONTENT_LENGTH=9999999999
    command: ["./wait-for-it.sh", "redis:6379", "--", "celery", "worker", "-l", "debug", "-A", "geo.tasks"]
    depends_on:
      - "redis"
      - "geo"
    volumes:
      - csv_files:/app/csv_files
    links:
      - "cassandra:cassandra"
      - "redis:redis"
  celery_images:
    image: kolbman.xyz:3333/images
    environment:
      - FLASK_CONFIG=production
      - FLASK_DEBUG
      - SECRET_KEY
      - SSL_DISABLE
      - GEO_URL=http://geo:5000
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_BACKEND=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SQLALCHEMY_DATABASE_URI=postgres://postgres:psql@postgres:5432/stoic
      - IMAGE_UPLOAD_DIR=/images
    command: ["celery", "worker", "-l", "debug", "-A", "images.tasks"]
    depends_on:
      - "redis"
      - "images"
    volumes:
      - image_uploads:/images
    links:
      - "geo:geo"
      - "pg:postgres"
      - "redis:redis"
  pg:
    image: postgres:9.6
    volumes:
      - pgdata:/var/log/postgresql/data
    environment:
      POSTGRES_DB: stoic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql
  redis:
    image: redis:3.2
  cassandra:
    image: cassandra:3.10
    environment:
      - CASSANDRA_START_RPC=true
    volumes:
      - cassandradata:/var/lib/cassandra
volumes:
  pgdata:
    driver: local
  cassandradata:
    driver: local
  csv_files:
    driver: local
  image_uploads:
    driver: local
